import Foundation
import AuthenticationServices
import Observation
#if canImport(UIKit)
import UIKit
#endif

/// Recreates v1's Imgur OAuth2 + album flow with async/await instead of the
/// old NotificationCenter + Combine plumbing. Same app credentials, same
/// "cataloger" callback URL scheme, same per-app hidden album.
@Observable
final class ImgurAuthManager: NSObject {
    static let shared = ImgurAuthManager()

    // Same Imgur app registration as v1.
    private let clientId = "2691de281566831"
    private let callbackScheme = "cataloger"

    private(set) var accessToken: String? {
        didSet { UserDefaults.standard.set(accessToken, forKey: "accessToken") }
    }
    private(set) var refreshToken: String? {
        didSet { UserDefaults.standard.set(refreshToken, forKey: "refreshToken") }
    }
    private(set) var userName: String? {
        didSet { UserDefaults.standard.set(userName, forKey: "userName") }
    }
    private(set) var albumId: String? {
        didSet { UserDefaults.standard.set(albumId, forKey: "albumId") }
    }

    var isLoggedIn: Bool { accessToken != nil }

    private var activeSession: ASWebAuthenticationSession?

    override init() {
        self.accessToken = UserDefaults.standard.string(forKey: "accessToken")
        self.refreshToken = UserDefaults.standard.string(forKey: "refreshToken")
        self.userName = UserDefaults.standard.string(forKey: "userName")
        self.albumId = UserDefaults.standard.string(forKey: "albumId")
        super.init()
    }

    enum AuthError: Error {
        case cancelled, parseFailed, notLoggedIn
    }

    @MainActor
    func login() async throws {
        let authURL = URL(string: "https://api.imgur.com/oauth2/authorize?client_id=\(clientId)&response_type=token&state=login")!

        let callbackURL: URL = try await withCheckedThrowingContinuation { continuation in
            let session = ASWebAuthenticationSession(url: authURL, callbackURLScheme: callbackScheme) { url, error in
                if let url {
                    continuation.resume(returning: url)
                } else {
                    continuation.resume(throwing: error ?? AuthError.cancelled)
                }
            }
            session.presentationContextProvider = self
            session.prefersEphemeralWebBrowserSession = false
            self.activeSession = session
            session.start()
        }

        // Token comes back in the URL fragment:
        // cataloger://?state=login#access_token=...&refresh_token=...&account_username=...
        guard let fragment = callbackURL.fragment else { throw AuthError.parseFailed }
        let params = Self.parseQueryFragment(fragment)
        guard let at = params["access_token"],
              let rt = params["refresh_token"],
              let un = params["account_username"] else {
            throw AuthError.parseFailed
        }
        accessToken = at
        refreshToken = rt
        userName = un
    }

    func logout() {
        accessToken = nil
        refreshToken = nil
        userName = nil
        albumId = nil
    }

    /// Ensures a per-app Imgur album exists, creating one (hidden, timestamped)
    /// on first use — mirrors v1's `creatNewAlbum()`.
    func ensureAlbum() async throws -> String {
        if let albumId { return albumId }
        return try await createNewAlbum()
    }
    @discardableResult
    func createNewAlbum() async throws -> String {
        guard let accessToken else { throw AuthError.notLoggedIn }

        var request = URLRequest(url: URL(string: "https://api.imgur.com/3/album")!)
        request.httpMethod = "POST"
        request.addValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")

        let formatter = DateFormatter()
        formatter.timeStyle = .medium
        formatter.dateStyle = .long
        let dateString = formatter.string(from: Date())
        let json: [String: String] = [
            "title": "Cataloger \(dateString)",
            "description": "automatically generated by cataloger on \(dateString)",
            "privacy": "hidden"
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: json)

        let (data, _) = try await URLSession.shared.data(for: request)
        guard let responseJSON = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let dataDict = responseJSON["data"] as? [String: Any],
              let id = dataDict["id"] as? String else {
            throw AuthError.parseFailed
        }
        albumId = id
        return id
    }

    private static func parseQueryFragment(_ fragment: String) -> [String: String] {
        var params = [String: String]()
        for item in fragment.split(separator: "&") {
            let combo = item.split(separator: "=")
            if combo.count == 2 { params[String(combo[0])] = String(combo[1]) }
        }
        return params
    }
}

extension ImgurAuthManager: ASWebAuthenticationPresentationContextProviding {
    func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        #if canImport(UIKit)
        return UIApplication.shared.connectedScenes
            .compactMap { ($0 as? UIWindowScene)?.keyWindow }
            .first ?? ASPresentationAnchor()
        #else
        return ASPresentationAnchor()
        #endif
    }
}
